CREATE TABLESPACE bd2_perm_01
DATAFILE 'bd2_perm_01.dat'
SIZE 20M
ONLINE;

CREATE TEMPORARY TABLESPACE bd2_temp_01
TEMPFILE 'bd2_temp_01.dbf'
SIZE 5M
AUTOEXTEND ON;

CREATE USER bd2
IDENTIFIED BY root
DEFAULT TABLESPACE bd2_perm_01
TEMPORARY TABLESPACE bd2_temp_01
QUOTA 20M on bd2_perm_01;

GRANT ALL PRIVILEGES TO bd2;